name: Continuous Integration (CI)

on:
  push:
    branches:
      - main  # Trigger on push to the 'main' branch
  pull_request:
    branches:
      - main  # Trigger on pull requests to the 'main' branch

jobs:
  test:
    name: Run Tests for Data Pipeline
    runs-on: ubuntu-latest  # Use Ubuntu runner for the job

    steps:
      # Step 1: Checkout the Code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Set Up Python Environment
      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'  # Specify the Python version

      # Step 3: Install Python Dependencies
      - name: Install Python Dependencies
        run: |
             python3 -m pip install --upgrade pip
             python3 -m pip install pandas
      # Step 4: Install Necessary System Packages
      - name: Install System Packages
        run: |
          sudo apt-get update
          sudo apt-get install -y curl bash  # Install required system tools

      # Step 5: Make tests.sh Executable
      - name: Make tests.sh Executable
        run: chmod +x ./project/tests.sh

      # Step 6: Run the Tests
      - name: Run Tests
        run: ./project/tests.sh
