name: Continuous Integration (CI)

on:
  push:
    branches:
      - main  # Trigger this action on push to the 'main' branch
  pull_request:
    branches:
      - main  # Trigger on pull requests to 'main' branch

jobs:
  test:
    runs-on: ubuntu-latest  # Runs the job on an Ubuntu runner

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Python 3
      - name: Set up Python 3
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  # You can specify 3.8, 3.9, etc., if needed

      # Step 3: Install dependencies from the 'project/requirements.txt'
      - name: Install dependencies
        run: |
          pip install -r project/requirements.txt  # Path to the requirements.txt in the 'project' folder

      # Step 4: Install necessary system packages (curl, bash, etc.)
      - name: Install necessary packages
        run: |
          sudo apt-get update
          sudo apt-get install -y curl bash

      # Step 5: Make tests.sh executable
      - name: Make tests.sh executable
        run: chmod +x ./project/tests.sh

      # Step 6: Run the tests.sh script
      - name: Run tests.sh
        run: ./project/tests.sh
